[env]
ZLIB_SRC = "1"
LIBGIT2_SYS_USE_PKG_CONFIG = "0"

[build]
rustflags = [
  "--remap-path-prefix=/home/runner/work/GitSync/GitSync=.",
  "--remap-path-prefix=/build/de.repoautofix.reposyncai=.",
  "--remap-path-prefix=/home/runner/.cargo/registry/src=/cargo/registry/src",
  "--remap-path-prefix=/root/.cargo/registry/src=/cargo/registry/src",
  "--remap-path-prefix=/home/vagrant/.cargo/registry/src=/cargo/registry/src",
  "-Ccodegen-units=1",
]
