// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_log`, `check`, `commit`, `configure_network_timeouts`, `ensure_empty_known_hosts`, `fast_forward`, `fetch_remote_priv`, `get_branch_name_priv`, `get_default_callbacks`, `get_staged_file_paths_priv`, `get_uncommitted_file_paths_priv`, `has_local_changes_priv`, `new`, `pull_changes_priv`, `push_changes_priv`, `run_with_lock`, `set_author`, `update_submodules_priv`, `was_stalled`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StallDetector`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `safe_wline`

Future<List<Commit>?> commitListRunWithLock({
  required String queueDir,
  required int index,
  required int priority,
  required String fnName,
  required FutureOr<List<Commit>?> Function() function,
}) => RustLib.instance.api.crateApiGitManagerCommitListRunWithLock(
  queueDir: queueDir,
  index: index,
  priority: priority,
  fnName: fnName,
  function: function,
);

Future<List<String>?> stringListRunWithLock({
  required String queueDir,
  required int index,
  required int priority,
  required String fnName,
  required FutureOr<List<String>?> Function() function,
}) => RustLib.instance.api.crateApiGitManagerStringListRunWithLock(
  queueDir: queueDir,
  index: index,
  priority: priority,
  fnName: fnName,
  function: function,
);

Future<List<(String, int)>?> stringIntListRunWithLock({
  required String queueDir,
  required int index,
  required int priority,
  required String fnName,
  required FutureOr<List<(String, int)>?> Function() function,
}) => RustLib.instance.api.crateApiGitManagerStringIntListRunWithLock(
  queueDir: queueDir,
  index: index,
  priority: priority,
  fnName: fnName,
  function: function,
);

Future<List<(String, ConflictType)>?> stringConflicttypeListRunWithLock({
  required String queueDir,
  required int index,
  required int priority,
  required String fnName,
  required FutureOr<List<(String, ConflictType)>?> Function() function,
}) => RustLib.instance.api.crateApiGitManagerStringConflicttypeListRunWithLock(
  queueDir: queueDir,
  index: index,
  priority: priority,
  fnName: fnName,
  function: function,
);

Future<(String, String)?> stringPairRunWithLock({
  required String queueDir,
  required int index,
  required int priority,
  required String fnName,
  required FutureOr<(String, String)?> Function() function,
}) => RustLib.instance.api.crateApiGitManagerStringPairRunWithLock(
  queueDir: queueDir,
  index: index,
  priority: priority,
  fnName: fnName,
  function: function,
);

Future<String?> stringRunWithLock({
  required String queueDir,
  required int index,
  required int priority,
  required String fnName,
  required FutureOr<String?> Function() function,
}) => RustLib.instance.api.crateApiGitManagerStringRunWithLock(
  queueDir: queueDir,
  index: index,
  priority: priority,
  fnName: fnName,
  function: function,
);

Future<int?> intRunWithLock({
  required String queueDir,
  required int index,
  required int priority,
  required String fnName,
  required FutureOr<int?> Function() function,
}) => RustLib.instance.api.crateApiGitManagerIntRunWithLock(
  queueDir: queueDir,
  index: index,
  priority: priority,
  fnName: fnName,
  function: function,
);

Future<bool?> boolRunWithLock({
  required String queueDir,
  required int index,
  required int priority,
  required String fnName,
  required FutureOr<bool?> Function() function,
}) => RustLib.instance.api.crateApiGitManagerBoolRunWithLock(
  queueDir: queueDir,
  index: index,
  priority: priority,
  fnName: fnName,
  function: function,
);

Future<void> voidRunWithLock({
  required String queueDir,
  required int index,
  required int priority,
  required String fnName,
  required FutureOr<void> Function() function,
}) => RustLib.instance.api.crateApiGitManagerVoidRunWithLock(
  queueDir: queueDir,
  index: index,
  priority: priority,
  fnName: fnName,
  function: function,
);

Future<String?> isLocked({required String queueDir, required int index}) =>
    RustLib.instance.api.crateApiGitManagerIsLocked(
      queueDir: queueDir,
      index: index,
    );

/// Clear stale queue files using flock-based liveness detection.
///
/// For each `flock_queue_{index}` file in the queues directory:
/// 1. Try a non-blocking exclusive flock on the corresponding `flock_active_{index}`.
/// 2. If the flock succeeds, no operation is actively running for that repo,
///    so the queue file is safe to truncate.
/// 3. If the flock fails (EWOULDBLOCK), an operation is in progress —
///    leave the queue file alone.
///
/// The OS automatically releases flocks when a process dies, so crashed
/// processes are correctly detected as "not running".
Future<void> clearStaleLocks({required String queueDir, required bool force}) =>
    RustLib.instance.api.crateApiGitManagerClearStaleLocks(
      queueDir: queueDir,
      force: force,
    );

Future<void> init({String? homepath}) =>
    RustLib.instance.api.crateApiGitManagerInit(homepath: homepath);

Future<List<String>> getSubmodulePaths({required String pathString}) => RustLib
    .instance
    .api
    .crateApiGitManagerGetSubmodulePaths(pathString: pathString);

Future<void> cloneRepository({
  required String url,
  required String pathString,
  required String provider,
  required (String, String) credentials,
  required (String, String) author,
  int? depth,
  required bool bare,
  required FutureOr<void> Function(String) cloneTaskCallback,
  required FutureOr<void> Function(int) cloneProgressCallback,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerCloneRepository(
  url: url,
  pathString: pathString,
  provider: provider,
  credentials: credentials,
  author: author,
  depth: depth,
  bare: bare,
  cloneTaskCallback: cloneTaskCallback,
  cloneProgressCallback: cloneProgressCallback,
  log: log,
);

Future<void> untrackAll({
  required String pathString,
  List<String>? filePaths,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerUntrackAll(
  pathString: pathString,
  filePaths: filePaths,
  log: log,
);

Future<Diff> getFileDiff({
  required String pathString,
  required String filePath,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGetFileDiff(
  pathString: pathString,
  filePath: filePath,
  log: log,
);

Future<Diff> getCommitDiff({
  required String pathString,
  required String startRef,
  String? endRef,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGetCommitDiff(
  pathString: pathString,
  startRef: startRef,
  endRef: endRef,
  log: log,
);

Future<WorkdirFileDiff> getWorkdirFileDiff({
  required String pathString,
  required String filePath,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGetWorkdirFileDiff(
  pathString: pathString,
  filePath: filePath,
  log: log,
);

Future<void> stageFileLines({
  required String pathString,
  required String filePath,
  required List<int> selectedLineIndices,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerStageFileLines(
  pathString: pathString,
  filePath: filePath,
  selectedLineIndices: selectedLineIndices,
  log: log,
);

Future<List<Commit>> getRecentCommits({
  required String pathString,
  required String remoteName,
  required Map<String, (int, int)> cachedDiffStats,
  required BigInt skip,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGetRecentCommits(
  pathString: pathString,
  remoteName: remoteName,
  cachedDiffStats: cachedDiffStats,
  skip: skip,
  log: log,
);

Future<List<String>> getCommitDiffStats({
  required String pathString,
  required List<String> references,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGetCommitDiffStats(
  pathString: pathString,
  references: references,
  log: log,
);

Future<void> updateSubmodules({
  required String pathString,
  required String provider,
  required (String, String) credentials,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerUpdateSubmodules(
  pathString: pathString,
  provider: provider,
  credentials: credentials,
  log: log,
);

Future<bool?> fetchRemote({
  required String pathString,
  required String remote,
  required String provider,
  required (String, String) credentials,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerFetchRemote(
  pathString: pathString,
  remote: remote,
  provider: provider,
  credentials: credentials,
  log: log,
);

Future<bool?> pullChanges({
  required String pathString,
  required String provider,
  required (String, String) credentials,
  (String, String)? commitSigningCredentials,
  required FutureOr<void> Function() syncCallback,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerPullChanges(
  pathString: pathString,
  provider: provider,
  credentials: credentials,
  commitSigningCredentials: commitSigningCredentials,
  syncCallback: syncCallback,
  log: log,
);

Future<bool?> downloadChanges({
  required String pathString,
  required String remote,
  required String provider,
  required (String, String) credentials,
  (String, String)? commitSigningCredentials,
  required (String, String) author,
  required FutureOr<void> Function() syncCallback,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerDownloadChanges(
  pathString: pathString,
  remote: remote,
  provider: provider,
  credentials: credentials,
  commitSigningCredentials: commitSigningCredentials,
  author: author,
  syncCallback: syncCallback,
  log: log,
);

Future<bool?> pushChanges({
  required String pathString,
  required String remoteName,
  required String provider,
  required (String, String) credentials,
  required FutureOr<void> Function() mergeConflictCallback,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerPushChanges(
  pathString: pathString,
  remoteName: remoteName,
  provider: provider,
  credentials: credentials,
  mergeConflictCallback: mergeConflictCallback,
  log: log,
);

Future<void> stageFilePaths({
  required String pathString,
  required List<String> paths,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerStageFilePaths(
  pathString: pathString,
  paths: paths,
  log: log,
);

Future<void> unstageFilePaths({
  required String pathString,
  required List<String> paths,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerUnstageFilePaths(
  pathString: pathString,
  paths: paths,
  log: log,
);

Future<int?> getRecommendedAction({
  required String pathString,
  required String remoteName,
  required String provider,
  required (String, String) credentials,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGetRecommendedAction(
  pathString: pathString,
  remoteName: remoteName,
  provider: provider,
  credentials: credentials,
  log: log,
);

Future<void> commitChanges({
  required String pathString,
  (String, String)? commitSigningCredentials,
  required (String, String) author,
  required String syncMessage,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerCommitChanges(
  pathString: pathString,
  commitSigningCredentials: commitSigningCredentials,
  author: author,
  syncMessage: syncMessage,
  log: log,
);

Future<bool?> uploadChanges({
  required String pathString,
  required String remoteName,
  required String provider,
  required (String, String) credentials,
  (String, String)? commitSigningCredentials,
  required (String, String) author,
  List<String>? filePaths,
  required String syncMessage,
  required FutureOr<void> Function() syncCallback,
  required FutureOr<void> Function() mergeConflictCallback,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerUploadChanges(
  pathString: pathString,
  remoteName: remoteName,
  provider: provider,
  credentials: credentials,
  commitSigningCredentials: commitSigningCredentials,
  author: author,
  filePaths: filePaths,
  syncMessage: syncMessage,
  syncCallback: syncCallback,
  mergeConflictCallback: mergeConflictCallback,
  log: log,
);

Future<void> forcePull({
  required String pathString,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerForcePull(
  pathString: pathString,
  log: log,
);

Future<void> forcePush({
  required String pathString,
  required String remoteName,
  required String provider,
  required (String, String) credentials,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerForcePush(
  pathString: pathString,
  remoteName: remoteName,
  provider: provider,
  credentials: credentials,
  log: log,
);

Future<void> uploadAndOverwrite({
  required String pathString,
  required String remoteName,
  required String provider,
  required (String, String) credentials,
  (String, String)? commitSigningCredentials,
  required (String, String) author,
  required String syncMessage,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerUploadAndOverwrite(
  pathString: pathString,
  remoteName: remoteName,
  provider: provider,
  credentials: credentials,
  commitSigningCredentials: commitSigningCredentials,
  author: author,
  syncMessage: syncMessage,
  log: log,
);

Future<void> downloadAndOverwrite({
  required String pathString,
  required String remoteName,
  required String provider,
  required (String, String) credentials,
  required (String, String) author,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerDownloadAndOverwrite(
  pathString: pathString,
  remoteName: remoteName,
  provider: provider,
  credentials: credentials,
  author: author,
  log: log,
);

Future<void> discardChanges({
  required String pathString,
  required List<String> filePaths,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerDiscardChanges(
  pathString: pathString,
  filePaths: filePaths,
  log: log,
);

Future<List<(String, ConflictType)>> getConflicting({
  required String pathString,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGetConflicting(
  pathString: pathString,
  log: log,
);

Future<List<(String, int)>> getStagedFilePaths({
  required String pathString,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGetStagedFilePaths(
  pathString: pathString,
  log: log,
);

Future<List<(String, int)>> getUncommittedFilePaths({
  required String pathString,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGetUncommittedFilePaths(
  pathString: pathString,
  log: log,
);

Future<void> abortMerge({
  required String pathString,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerAbortMerge(
  pathString: pathString,
  log: log,
);

Future<(String, String)> generateSshKey({
  required String format,
  required String passphrase,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGenerateSshKey(
  format: format,
  passphrase: passphrase,
  log: log,
);

Future<String?> getBranchName({
  required String pathString,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGetBranchName(
  pathString: pathString,
  log: log,
);

Future<List<String>> getBranchNames({
  required String pathString,
  required String remote,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerGetBranchNames(
  pathString: pathString,
  remote: remote,
  log: log,
);

Future<void> setRemoteUrl({
  required String pathString,
  required String remoteName,
  required String newRemoteUrl,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerSetRemoteUrl(
  pathString: pathString,
  remoteName: remoteName,
  newRemoteUrl: newRemoteUrl,
  log: log,
);

Future<List<String>> listRemotes({
  required String pathString,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerListRemotes(
  pathString: pathString,
  log: log,
);

Future<void> initRepository({
  required String pathString,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerInitRepository(
  pathString: pathString,
  log: log,
);

Future<void> setHeadToBranch({
  required String pathString,
  required String branchName,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerSetHeadToBranch(
  pathString: pathString,
  branchName: branchName,
  log: log,
);

Future<void> addRemote({
  required String pathString,
  required String remoteName,
  required String remoteUrl,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerAddRemote(
  pathString: pathString,
  remoteName: remoteName,
  remoteUrl: remoteUrl,
  log: log,
);

Future<void> deleteRemote({
  required String pathString,
  required String remoteName,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerDeleteRemote(
  pathString: pathString,
  remoteName: remoteName,
  log: log,
);

Future<void> renameRemote({
  required String pathString,
  required String oldName,
  required String newName,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerRenameRemote(
  pathString: pathString,
  oldName: oldName,
  newName: newName,
  log: log,
);

Future<void> checkoutBranch({
  required String pathString,
  required String remote,
  required String branchName,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerCheckoutBranch(
  pathString: pathString,
  remote: remote,
  branchName: branchName,
  log: log,
);

Future<bool> getDisableSsl({required String gitDir}) =>
    RustLib.instance.api.crateApiGitManagerGetDisableSsl(gitDir: gitDir);

Future<void> setDisableSsl({required String gitDir, required bool disable}) =>
    RustLib.instance.api.crateApiGitManagerSetDisableSsl(
      gitDir: gitDir,
      disable: disable,
    );

Future<void> createBranch({
  required String pathString,
  required String newBranchName,
  required String remoteName,
  required String sourceBranchName,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerCreateBranch(
  pathString: pathString,
  newBranchName: newBranchName,
  remoteName: remoteName,
  sourceBranchName: sourceBranchName,
  log: log,
);

Future<void> renameBranch({
  required String pathString,
  required String oldName,
  required String newName,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerRenameBranch(
  pathString: pathString,
  oldName: oldName,
  newName: newName,
  log: log,
);

Future<void> deleteBranch({
  required String pathString,
  required String branchName,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerDeleteBranch(
  pathString: pathString,
  branchName: branchName,
  log: log,
);

Future<void> recreateDeletedIndex({required String pathString}) => RustLib
    .instance
    .api
    .crateApiGitManagerRecreateDeletedIndex(pathString: pathString);

Future<void> pruneCorruptedLooseObjects({required String pathString}) => RustLib
    .instance
    .api
    .crateApiGitManagerPruneCorruptedLooseObjects(pathString: pathString);

Future<void> createBranchFromCommit({
  required String pathString,
  required String newBranchName,
  required String commitSha,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerCreateBranchFromCommit(
  pathString: pathString,
  newBranchName: newBranchName,
  commitSha: commitSha,
  log: log,
);

Future<void> checkoutCommit({
  required String pathString,
  required String commitSha,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerCheckoutCommit(
  pathString: pathString,
  commitSha: commitSha,
  log: log,
);

Future<void> createTag({
  required String pathString,
  required String tagName,
  required String commitSha,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerCreateTag(
  pathString: pathString,
  tagName: tagName,
  commitSha: commitSha,
  log: log,
);

Future<void> revertCommit({
  required String pathString,
  required String commitSha,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerRevertCommit(
  pathString: pathString,
  commitSha: commitSha,
  log: log,
);

Future<void> amendCommit({
  required String pathString,
  required String newMessage,
  String? authorName,
  String? authorEmail,
  (String, String)? commitSigningCredentials,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerAmendCommit(
  pathString: pathString,
  newMessage: newMessage,
  authorName: authorName,
  authorEmail: authorEmail,
  commitSigningCredentials: commitSigningCredentials,
  log: log,
);

Future<void> undoCommit({
  required String pathString,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerUndoCommit(
  pathString: pathString,
  log: log,
);

Future<void> resetToCommit({
  required String pathString,
  required String commitSha,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerResetToCommit(
  pathString: pathString,
  commitSha: commitSha,
  log: log,
);

Future<void> cherryPickCommit({
  required String pathString,
  required String commitSha,
  required String targetBranch,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerCherryPickCommit(
  pathString: pathString,
  commitSha: commitSha,
  targetBranch: targetBranch,
  log: log,
);

Future<void> squashCommits({
  required String pathString,
  required String oldestCommitSha,
  required String squashMessage,
  (String, String)? commitSigningCredentials,
  required FutureOr<void> Function(LogType, String) log,
}) => RustLib.instance.api.crateApiGitManagerSquashCommits(
  pathString: pathString,
  oldestCommitSha: oldestCommitSha,
  squashMessage: squashMessage,
  commitSigningCredentials: commitSigningCredentials,
  log: log,
);

abstract class WithLine {
  Future<WithLine> safeWline({required int line});
}

class Commit {
  final PlatformInt64 timestamp;
  final String authorUsername;
  final String authorEmail;
  final String reference;
  final String commitMessage;
  final int additions;
  final int deletions;
  final bool unpulled;
  final bool unpushed;
  final List<String> tags;

  const Commit({
    required this.timestamp,
    required this.authorUsername,
    required this.authorEmail,
    required this.reference,
    required this.commitMessage,
    required this.additions,
    required this.deletions,
    required this.unpulled,
    required this.unpushed,
    required this.tags,
  });

  @override
  int get hashCode =>
      timestamp.hashCode ^
      authorUsername.hashCode ^
      authorEmail.hashCode ^
      reference.hashCode ^
      commitMessage.hashCode ^
      additions.hashCode ^
      deletions.hashCode ^
      unpulled.hashCode ^
      unpushed.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Commit &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          authorUsername == other.authorUsername &&
          authorEmail == other.authorEmail &&
          reference == other.reference &&
          commitMessage == other.commitMessage &&
          additions == other.additions &&
          deletions == other.deletions &&
          unpulled == other.unpulled &&
          unpushed == other.unpushed &&
          tags == other.tags;
}

enum ConflictType { text }

class Diff {
  final int insertions;
  final int deletions;
  final Map<String, Map<String, String>> diffParts;

  const Diff({
    required this.insertions,
    required this.deletions,
    required this.diffParts,
  });

  static Future<Diff> default_() =>
      RustLib.instance.api.crateApiGitManagerDiffDefault();

  @override
  int get hashCode =>
      insertions.hashCode ^ deletions.hashCode ^ diffParts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Diff &&
          runtimeType == other.runtimeType &&
          insertions == other.insertions &&
          deletions == other.deletions &&
          diffParts == other.diffParts;
}

enum LogType {
  test,
  global,
  accessibilityService,
  selectDirectory,
  getRepos,
  sync_,
  syncException,
  clone,
  updateSubmodules,
  fetchRemote,
  pullFromRepo,
  stage,
  unstage,
  recommendedAction,
  commit,
  pushToRepo,
  forcePull,
  forcePush,
  downloadAndOverwrite,
  uploadAndOverwrite,
  discardChanges,
  untrackAll,
  commitDiff,
  fileDiff,
  recentCommits,
  conflictingFiles,
  uncommittedFiles,
  stagedFiles,
  abortMerge,
  branchName,
  branchNames,
  setRemoteUrl,
  checkoutBranch,
  createBranch,
  renameBranch,
  deleteBranch,
  readGitIgnore,
  writeGitIgnore,
  readGitInfoExclude,
  writeGitInfoExclude,
  getDisableSsl,
  setDisableSsl,
  generateKeyPair,
  getRemoteUrlLink,
  discardDir,
  discardGitIndex,
  discardFetchHead,
  pruneCorruptedObjects,
  getSubmodules,
  hasGitFilters,
  downloadChanges,
  uploadChanges,
  listRemotes,
  addRemote,
  deleteRemote,
  renameRemote,
  initRepo,
  createBranchFromCommit,
  checkoutCommit,
  createTag,
  revertCommit,
  amendCommit,
  undoCommit,
  resetToCommit,
  cherryPickCommit,
  squashCommits,
  workdirFileDiff,
  stageFileLines,
}

class WorkdirDiffLine {
  final int lineIndex;
  final String origin;
  final String content;
  final int oldLineno;
  final int newLineno;
  final bool isStaged;

  const WorkdirDiffLine({
    required this.lineIndex,
    required this.origin,
    required this.content,
    required this.oldLineno,
    required this.newLineno,
    required this.isStaged,
  });

  @override
  int get hashCode =>
      lineIndex.hashCode ^
      origin.hashCode ^
      content.hashCode ^
      oldLineno.hashCode ^
      newLineno.hashCode ^
      isStaged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkdirDiffLine &&
          runtimeType == other.runtimeType &&
          lineIndex == other.lineIndex &&
          origin == other.origin &&
          content == other.content &&
          oldLineno == other.oldLineno &&
          newLineno == other.newLineno &&
          isStaged == other.isStaged;
}

class WorkdirFileDiff {
  final String filePath;
  final int insertions;
  final int deletions;
  final bool isBinary;
  final List<WorkdirDiffLine> lines;

  const WorkdirFileDiff({
    required this.filePath,
    required this.insertions,
    required this.deletions,
    required this.isBinary,
    required this.lines,
  });

  @override
  int get hashCode =>
      filePath.hashCode ^
      insertions.hashCode ^
      deletions.hashCode ^
      isBinary.hashCode ^
      lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkdirFileDiff &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          insertions == other.insertions &&
          deletions == other.deletions &&
          isBinary == other.isBinary &&
          lines == other.lines;
}
